/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AgreementsRouteImport } from './routes/agreements'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AgentIdRouteImport } from './routes/agent.$id'
import { Route as AgreementIdRouteImport } from './routes/agreement.$id'
import { Route as AgreementsIndexRouteImport } from './routes/agreements.index'
import { Route as AgreementsNewRouteImport } from './routes/agreements.new'
import { Route as ApiPrepareEvidenceRouteImport } from './routes/api.prepare-evidence'
import { Route as CaseIdRouteImport } from './routes/case.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementsRoute = AgreementsRouteImport.update({
  id: '/agreements',
  path: '/agreements',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIdRoute = AgentIdRouteImport.update({
  id: '/agent/$id',
  path: '/agent/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementIdRoute = AgreementIdRouteImport.update({
  id: '/agreement/$id',
  path: '/agreement/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementsIndexRoute = AgreementsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgreementsRoute,
} as any)
const AgreementsNewRoute = AgreementsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AgreementsRoute,
} as any)
const ApiPrepareEvidenceRoute = ApiPrepareEvidenceRouteImport.update({
  id: '/api/prepare-evidence',
  path: '/api/prepare-evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseIdRoute = CaseIdRouteImport.update({
  id: '/case/$id',
  path: '/case/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/agreements': typeof AgreementsRouteWithChildren
  '/cases': typeof CasesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/register': typeof RegisterRoute
  '/agent/$id': typeof AgentIdRoute
  '/agreement/$id': typeof AgreementIdRoute
  '/agreements/new': typeof AgreementsNewRoute
  '/api/prepare-evidence': typeof ApiPrepareEvidenceRoute
  '/case/$id': typeof CaseIdRoute
  '/agreements/': typeof AgreementsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/cases': typeof CasesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/register': typeof RegisterRoute
  '/agent/$id': typeof AgentIdRoute
  '/agreement/$id': typeof AgreementIdRoute
  '/agreements/new': typeof AgreementsNewRoute
  '/api/prepare-evidence': typeof ApiPrepareEvidenceRoute
  '/case/$id': typeof CaseIdRoute
  '/agreements': typeof AgreementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/agreements': typeof AgreementsRouteWithChildren
  '/cases': typeof CasesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/register': typeof RegisterRoute
  '/agent/$id': typeof AgentIdRoute
  '/agreement/$id': typeof AgreementIdRoute
  '/agreements/new': typeof AgreementsNewRoute
  '/api/prepare-evidence': typeof ApiPrepareEvidenceRoute
  '/case/$id': typeof CaseIdRoute
  '/agreements/': typeof AgreementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/agreements'
    | '/cases'
    | '/how-it-works'
    | '/register'
    | '/agent/$id'
    | '/agreement/$id'
    | '/agreements/new'
    | '/api/prepare-evidence'
    | '/case/$id'
    | '/agreements/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/cases'
    | '/how-it-works'
    | '/register'
    | '/agent/$id'
    | '/agreement/$id'
    | '/agreements/new'
    | '/api/prepare-evidence'
    | '/case/$id'
    | '/agreements'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/agreements'
    | '/cases'
    | '/how-it-works'
    | '/register'
    | '/agent/$id'
    | '/agreement/$id'
    | '/agreements/new'
    | '/api/prepare-evidence'
    | '/case/$id'
    | '/agreements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  AgreementsRoute: typeof AgreementsRouteWithChildren
  CasesRoute: typeof CasesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  RegisterRoute: typeof RegisterRoute
  AgentIdRoute: typeof AgentIdRoute
  AgreementIdRoute: typeof AgreementIdRoute
  ApiPrepareEvidenceRoute: typeof ApiPrepareEvidenceRoute
  CaseIdRoute: typeof CaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreements': {
      id: '/agreements'
      path: '/agreements'
      fullPath: '/agreements'
      preLoaderRoute: typeof AgreementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$id': {
      id: '/agent/$id'
      path: '/agent/$id'
      fullPath: '/agent/$id'
      preLoaderRoute: typeof AgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreement/$id': {
      id: '/agreement/$id'
      path: '/agreement/$id'
      fullPath: '/agreement/$id'
      preLoaderRoute: typeof AgreementIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreements/': {
      id: '/agreements/'
      path: '/'
      fullPath: '/agreements/'
      preLoaderRoute: typeof AgreementsIndexRouteImport
      parentRoute: typeof AgreementsRoute
    }
    '/agreements/new': {
      id: '/agreements/new'
      path: '/new'
      fullPath: '/agreements/new'
      preLoaderRoute: typeof AgreementsNewRouteImport
      parentRoute: typeof AgreementsRoute
    }
    '/api/prepare-evidence': {
      id: '/api/prepare-evidence'
      path: '/api/prepare-evidence'
      fullPath: '/api/prepare-evidence'
      preLoaderRoute: typeof ApiPrepareEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$id': {
      id: '/case/$id'
      path: '/case/$id'
      fullPath: '/case/$id'
      preLoaderRoute: typeof CaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgreementsRouteChildren {
  AgreementsNewRoute: typeof AgreementsNewRoute
  AgreementsIndexRoute: typeof AgreementsIndexRoute
}

const AgreementsRouteChildren: AgreementsRouteChildren = {
  AgreementsNewRoute: AgreementsNewRoute,
  AgreementsIndexRoute: AgreementsIndexRoute,
}

const AgreementsRouteWithChildren = AgreementsRoute._addFileChildren(
  AgreementsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  AgreementsRoute: AgreementsRouteWithChildren,
  CasesRoute: CasesRoute,
  HowItWorksRoute: HowItWorksRoute,
  RegisterRoute: RegisterRoute,
  AgentIdRoute: AgentIdRoute,
  AgreementIdRoute: AgreementIdRoute,
  ApiPrepareEvidenceRoute: ApiPrepareEvidenceRoute,
  CaseIdRoute: CaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
